FactoryBot.define do
  factory :women_answer do
    body_type 1
    ss_size 1
    ss_fit 1
    ls_size 1
    ls_fit 1
    vj_size 1
    vj_fit 1
    sprt_bra_size 1
    sprt_bra_fit 1
    sprt_bra_construction 1
    sprt_bra_straps 1
    sprt_bra_support 1
    bad_sprt_bra_materials 1
    bad_sprt_bra_material_name "MyString"
    sprt_bra_frequency 1
    short_size 1
    short_fit 1
    pant_tight_size 1
    pant_tight_fit 1
    shoe_size 1
    glove_size 1
    hat_style 1
    hat_size 1
    top_fit 1
    short_fit 1
    short_length 1
    pant_fit 1
    quad_size 1
    pant_length 1
    sleeve_length_issue 1
    pant_length_issue 1
    sock_height 1
    built_in_underwear 1
    hot_or_cold 1
    workout_conditions 1
    bad_colors 1
    bad_materials 1
    short_pockets_preference 1
    running_short_side_splits 1
    phone_carry_place 1
    new_trend 1
    new_trend_text "MyString"
    upcoming_event 1
    upcoming_event_name "MyString"
    upcoming_event_date "MyString"
    sport_choice_for_box 1
    box_frequency 1
    ss_need 1
    ls_need 1
    tank_need 1
    vest_need 1
    jacket_need 1
    short_need 1
    pant_need 1
    hat_need 1
    glove_need 1
    sock_need 1
    instagram_yn 1
    instagram "MyString"
    anything_else "MyText"
  end
end
