class SurveyAnswer < ApplicationRecord
  belongs_to :user
  enum gender: [:men, :women]
  enum body_type: [:pear, :apple_round, :straight_no_curves, :hourglass, :slim, :average, :athletic, :husky]
  enum ss_size: [:extra_small, :small, :medium, :large, :extra_large]
  enum ls_size: [:extra_small, :small, :medium, :large, :extra_large]
  enum vj_size: [:extra_small, :small, :medium, :large, :extra_large]
  enum sprt_bra_size: [:extra_small, :small, :medium, :large, :extra_large]
  enum sprt_bra_construction: [:underwire, :seamless, :a_bit_of_both, :no_preference]
  enum sport_bra_encapsulation: [:encapsulation, :compression, :encapsulation_and_compression, :no_preference]
  enum sprt_bra_straps: [:crisscross, :tanktop, :racerback]
  enum sprt_bra_support: [:minimal, :medium, :a_lot]
  enum bad_sprt_bra_materials: [:cotton, :coolmax, :spandex, :other]
  enum sprt_bra_frequency: [:send_now, :happy_to_try, :dont_need]
  enum short_size: [:extra_small, :small, :medium, :large, :extra_large]
  enum pant_tight_size: [:extra_small, :small, :medium, :large, :extra_large]
  enum glove_size: [:extra_small, :small, :medium, :large, :extra_large]
  enum hat_style: [:trucker, :ballcap, :skiing_beanie, :running_beanie, :visor]
  enum hat_size: [:big, :avg, :small]
  enum top_fit: [:form_fit, :form_fit_but_loose, :little_loose, :baggy]
  enum short_form_fit: [:form_fit, :form_fit_but_loose, :little_loose, :baggy]
  enum short_length: [:short, :mid, :knee]
  enum pant_tight_form_fit: [:form_fit, :form_fit_but_loose, :little_loose, :baggy]
  enum pant_length: [:ankles, :capri, :tights, :baggy, :yoga]
  enum sleeve_length_issue: [:too_long, :too_short, :just_right]
  enum pant_length_issue: [:too_long, :too_short, :just_right]
  enum sock_height: [:no_show, :low_ankle, :mid_ankle, :crew_calf, :tall, :compression]
  enum built_in_underwear: [:yes, :no]
  enum hot_or_cold: [:hot, :cold, :neither]
  enum workout_conditions: [:hot, :cold, :rain, :indoors, :seasonal]
  enum bad_colors: [:black, :brown, :green, :blue, :yellow, :orange, :red, :pink, :purple]
  enum bad_materials: [:cotton, :wool, :coolmax, :spandex]
  enum short_pockets_preference: [:none, :rear_zip, :key_pocket, :no_preference]
  enum running_short_side_splits: [:prefer, :dislike, :either, :no_preference]
  enum phone_carry_place: [:no_phone, :hands, :shorts, :phone_holder]
  enum new_trend: [:yes, :no]
  enum upcoming_event: [:yes, :no]
  enum sport_choice_for_box: [:road, :trail, :hike, :cycling, :swimming, :gym, :tri]
  enum box_frequency: [:b4race, :per_month,  :per_quarter, :twice_yearly]
  enum ss_need: [:send_now, :happy_to_try, :dont_need]
  enum ls_need: [:send_now, :happy_to_try, :dont_need]
  enum tank_need: [:send_now, :happy_to_try, :dont_need]
  enum vest_need: [:send_now, :happy_to_try, :dont_need]
  enum jacket_need: [:send_now, :happy_to_try, :dont_need]
  enum short_need: [:send_now, :happy_to_try, :dont_need]
  enum pant_need: [:send_now, :happy_to_try, :dont_need]
  enum hat_need: [:send_now, :happy_to_try, :dont_need]
  enum glove_need: [:send_now, :happy_to_try, :dont_need]
  enum sock_need: [:send_now, :happy_to_try, :dont_need]
  enum instagram_yn: [:yes, :no]
end
